name: Automated Builds

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
      with:
        cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Restore DataGen cache
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: src/main/generated
        key: datagen-${{ github.run_id }}
        restore-keys:
          datagen-

    - name: Run DataGen
      run: ./gradlew runDatagen

    - name: Save DataGen cache
      id: cache-save
      uses: actions/cache/save@v4
      with:
        path: src/main/generated
        key: ${{ steps.cache-restore.outputs.cache-primary-key }}

    - name: Build
      run: ./gradlew build

    - name: Publish to Discord
      uses: drtheodor/discord-webhook-upload-action@v0.2
      with:
        url: ${{ secrets.DEV_BUILDS }}
        file: |
          build/libs/*.jar
          !build/libs/*-sources.jar
        username: its tronning time
        avatar: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Jared_Leto_by_Gage_Skidmore_2.jpg/1024px-Jared_Leto_by_Gage_Skidmore_2.jpg'
        message_commit: '> :sparkles: [${commitMessage}](<${commitUrl}>) by [${authorName}](<${authorUrl}>)'
        message_header: |
          <:new1:1253371736510959636><:new2:1253371805734015006> New `${{ github.repository }}` dev build `#${{ github.run_number }}`:
